import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import Appsidebar from "./_components/Appsidebar";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import ThemeToggleButton from "./(routes)/search/[libid]/_components/ThemeToggleButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Perplexity-ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          {/*  Sets theme based on localStorage or prefers-color-scheme */}
          <script
            dangerouslySetInnerHTML={{
              __html: `
                try {
                  const theme = localStorage.getItem("theme");
                  if (theme === "dark" || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                    document.documentElement.classList.add("dark");
                  } else {
                    document.documentElement.classList.remove("dark");
                  }
                } catch(_) {}
              `,
            }}
          />
        </head>
        <body
          className={`bg-background text-foreground transition-colors duration-300 ${geistSans.variable} ${geistMono.variable}`}
        >
          <SidebarProvider>
            <ThemeToggleButton /> {/*  Toggle is handled properly in a client component */}

            <Appsidebar />
            <SidebarInset>
              <main className="transition-all duration-300 ease-in-out flex gap-1">
                <SidebarTrigger />
                <Provider>
                  <div className="flex-1">{children}</div>
                </Provider>
              </main>
            </SidebarInset>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
// © 2025 Ishikaa Goyal. All rights reserved.

